# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
